---
title: "Data Cleaning"
author: "Junyao Shi (js3453)"
date: "February 11, 2018"
output: pdf_document
---


```{r}
#Anna's reading data 
#library(readr)
#data <- read_csv("~/Desktop/stsci599/Healthy Weight Registry.csv")

data = read.csv("C:/Users/shall/Desktop/Cornell_MPS/MPS Project/Healthy Weight Registry.csv", header = T)
head(data)

#delete columns that all records are "*******"
t = apply(data == "*******", 2, sum)
data = data[,- which(t == length(data[,1]))]
head(data)
attach(data)

#delete the column Distribution.Channel because 1414 records are 'anonymous' and one is null
#delete the column Response.Type because 1414 records are 'IP Adress' and one is null
data = data[,- which(names(data) %in% c('Distribution.Channel', 'Response.Type'))]
head(data)
attach(data)

#delete who said no to 'Statement.of.Consent..I.have.read.the.above.information..and.have.received.answers.to.any.questions.I.asked.'
data = data[-which(grepl('No', Statement.of.Consent..I.have.read.the.above.information..and.have.received.answers.to.any.questions.I.asked.)),]
length(data[,1])
head(data)

#delete those whose duration in seconds are at the bottom 25% or top 10% 
boxplot(Duration..in.seconds.)
data = data[-which(Duration..in.seconds. %in% sort(Duration..in.seconds.)[1:floor(0.25 * length(Duration..in.seconds.))] | Duration..in.seconds. %in% sort(Duration..in.seconds., decreasing = TRUE)[1:floor(0.1 * length(Duration..in.seconds.))]),]
head(data)
length(data[,1])

#delete those duplicated emails
e = We.d.like.to.start.off.by.asking.for.your.name.and.email...Email[which(duplicated(	
We.d.like.to.start.off.by.asking.for.your.name.and.email...Email) == TRUE & 	
We.d.like.to.start.off.by.asking.for.your.name.and.email...Email != '')]
#not sure which duplicated ones should be deleted
```

```{r}

#delete columns where more than 50% was left blank
data[, -which(colMeans(is.na(data)) > 0.5)]

#delete rows where more than 50% was left blank
data[-which(rowMeans(is.na(data)) > 0.5),]


#create a new row called bmi   
#delete people with unreasonable heights, weights, ages

data$`What is your weight? - Weight - Weight`
data$`What is your height? - Height - Height`

hist(data$BMI_kg_cm)
data = subset(data, data$BMI_kg_cm >50)



```









